name: Issue
description: File a bug report
body:
  - type: checkboxes
    attributes:
      label: Confirmations
      options:
        - label: I can verify that I am running the mod on the latest possible Minecraft version.
          required: true
        - label: I can verify that the issue I am reporting exists on the latest possible Mod version.
          required: true
  - type: input
    attributes:
      label: Mod version (NOT Minecraft version)
      description: Please do not put "latest,", "newest," or some other vague indicator.
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Mod Name
      description: This repo contains all the mod reports. I need to know which mod you are reporting.
      options:
        - Penomior
        - SypWid
    validations:
      required: true
  - type: textarea
    attributes:
      label: A description of the issue
    validations:
      required: true
  - type: input
    attributes:
      label: Log or crash report
      description: Please use [gist](https://gist.github.com/).
    validations:
      required: true
